#version: "3"
#services:
#  frontend:
#    image: nginx:alpine
#    ports:
#      - "80:80"
#    volumes:
#      - ./frontend:/usr/share/nginx/html
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8080"

version: "3"
services:
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - frontend-code:/usr/share/nginx/html
    networks:
     - frontend-backend-network
    environment:
      - NGINX_HOST=frontend.example.com
      - NGINX_PORT=80


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - backend-code:/app
    networks:
      - frontend-backend-network
    environment:
      - API_KEY=your_api_key

volumes:
  frontend-code:
  backend-code:

networks:
  frontend-backend-network:
    driver: bridge



